### PR TITLE
Rebase on Node v18.10.0

### PR DESCRIPTION
**Pull request by gmaclennan**
This is an attempt to rebase the changes to nodejs-mobile onto upstream Node v18.10.0. This is using the same approach as #3 by applying the diff [`upstream-node-v12.19.0...mobile-master`](https://github.com/nodejs-mobile/nodejs-mobile/compare/upstream-node-v12.19.0...mobile-master.diff) onto v18.10.0 from upstream. I am going through each file one-by-one and manually resolving differences. Some patches apply cleanly, in other cases sometimes code has been removed, or changed order. Once the patch is applied we can see whether it compiles and then have a starting point for modifying the patches to work. I will keep the task list below updated as I go through each file.

**Modified**

- [ ] README.md
- [ ] android-configure
- [x] common.gypi
- [x] configure.py
- [x] deps/cares/cares.gyp
- [x] deps/cares/config/android/ares_config.h
- [x] deps/openssl/config/opensslconf.h
- [x] deps/openssl/openssl_no_asm.gypi
- [x] deps/uv/include/uv/android-ifaddrs.h
- [x] deps/uv/src/unix/android-ifaddrs.c
- [x] deps/uv/src/unix/darwin.c
- [x] deps/uv/src/unix/fs.c
- [x] deps/uv/src/unix/linux-core.c
- [x] deps/uv/uv.gyp
- [x] deps/uvwasi/src/uvwasi.c
- [x] deps/v8/src/base/platform/platform-posix.cc
- [x] doc/api/os.md
- [x] node.gyp
- [x] node.gypi
- [x] src/debug_utils.cc
- [x] src/node.cc
- [x] src/node_credentials.cc
- [x] src/node_env_var.cc
- [x] src/node_internals.h
- [x] src/node_metadata.cc
- [x] src/node_metadata.h
- [x] src/node_version.h
- [x] test/common/index.js
- [x] test/message/message.status
- [x] test/message/testcfg.py
- [x] test/parallel/parallel.status
- [x] test/parallel/test-assert-deep.js
- [x] test/parallel/test-assert.js
- [x] test/parallel/test-dgram-bind-fd.js
- [x] test/parallel/test-dgram-membership.js
- [x] test/parallel/test-dgram-socket-buffer-size.js
- [x] test/parallel/test-fs-copyfile.js
- [x] test/parallel/test-fs-lchmod.js
- [x] test/parallel/test-fs-mkdir.js
- [x] test/parallel/test-fs-open-flags.js
- [x] test/parallel/test-fs-promises.js
- [x] test/parallel/test-fs-read-file-sync-hostname.js
- [x] test/parallel/test-fs-readdir-stack-overflow.js
- [x] test/parallel/test-fs-readdir-ucs2.js
- [x] test/parallel/test-fs-realpath-native.js
- [x] test/parallel/test-fs-realpath.js
- [x] test/parallel/test-fs-rmdir-recursive.js
- [x] test/parallel/test-fs-stat.js
- [x] test/parallel/test-fs-watch.js
- [x] test/parallel/test-fs-watchfile.js
- [x] test/parallel/test-gc-http-client-onerror.js
- [x] test/parallel/test-http2-respond-file-error-dir.js
- [x] test/parallel/test-net-connect-options-fd.js
- [x] test/parallel/test-os.js
- [x] test/parallel/test-process-constants-noatime.js
- [x] test/parallel/test-process-versions.js
- [x] test/parallel/test-repl-options.js
- [x] test/parallel/test-signal-handler.js
- [x] test/parallel/test-util-types.js
- [x] test/parallel/test-v8-serdes.js
- [x] test/sequential/sequential.status
- [x] test/sequential/test-async-wrap-getasyncid.js
- [x] test/sequential/test-fs-watch.js
- [x] test/sequential/test-perf-hooks.js

**Added**

- [ ] .github/ISSUE_TEMPLATE.md
- [ ] FAQ.md
- [ ] NodeMobile.podspec
- [x] doc_mobile/CHANGELOG.md
- [x] doc_mobile/CONTRIBUTING.md
- [x] doc_mobile/TESTING.md
- [x] src/node_mobile_version.h
- [ ] tools/android_build.sh
- [ ] tools/ios-framework/NodeMobile.xcodeproj/project.pbxproj
- [ ] tools/ios-framework/NodeMobile.xcodeproj/project.xcworkspace/contents.xcworkspacedata
- [ ] tools/ios-framework/NodeMobile.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
- [ ] tools/ios-framework/NodeMobile.xcodeproj/project.xcworkspace/xcuserdata/jbernardo.xcuserdatad/UserInterfaceState.xcuserstate
- [ ] tools/ios-framework/NodeMobile.xcodeproj/xcuserdata/jbernardo.xcuserdatad/xcschemes/xcschememanagement.plist
- [ ] tools/ios-framework/NodeMobile/Info.plist
- [ ] tools/ios-framework/NodeMobile/NodeMobile.cpp
- [ ] tools/ios-framework/NodeMobile/NodeMobile.h
- [ ] tools/ios_framework_prepare.sh
- [ ] tools/mobile-test/android/node-android-proxy.sh
- [ ] tools/mobile-test/android/prepare-android-test.sh
- [ ] tools/mobile-test/android/testnode/.gitignore
- [ ] tools/mobile-test/android/testnode/app/.gitignore
- [ ] tools/mobile-test/android/testnode/app/CMakeLists.txt
- [ ] tools/mobile-test/android/testnode/app/build.gradle
- [ ] tools/mobile-test/android/testnode/app/proguard-rules.pro
- [ ] tools/mobile-test/android/testnode/app/src/main/AndroidManifest.xml
- [ ] tools/mobile-test/android/testnode/app/src/main/assets/main-test.js
- [ ] tools/mobile-test/android/testnode/app/src/main/cpp/native-lib.cpp
- [ ] tools/mobile-test/android/testnode/app/src/main/java/com/janeasystems/test/testnode/MainActivity.java
- [ ] tools/mobile-test/android/testnode/app/src/main/res/layout/activity_main.xml
- [ ] tools/mobile-test/android/testnode/app/src/main/res/mipmap-hdpi/ic_launcher.png
- [ ] tools/mobile-test/android/testnode/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
- [ ] tools/mobile-test/android/testnode/app/src/main/res/mipmap-mdpi/ic_launcher.png
- [ ] tools/mobile-test/android/testnode/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
- [ ] tools/mobile-test/android/testnode/app/src/main/res/mipmap-xhdpi/ic_launcher.png
- [ ] tools/mobile-test/android/testnode/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
- [ ] tools/mobile-test/android/testnode/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
- [ ] tools/mobile-test/android/testnode/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
- [ ] tools/mobile-test/android/testnode/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
- [ ] tools/mobile-test/android/testnode/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
- [ ] tools/mobile-test/android/testnode/app/src/main/res/values/colors.xml
- [ ] tools/mobile-test/android/testnode/app/src/main/res/values/strings.xml
- [ ] tools/mobile-test/android/testnode/app/src/main/res/values/styles.xml
- [ ] tools/mobile-test/android/testnode/build.gradle
- [ ] tools/mobile-test/android/testnode/gradle.properties
- [ ] tools/mobile-test/android/testnode/gradle/wrapper/gradle-wrapper.jar
- [ ] tools/mobile-test/android/testnode/gradle/wrapper/gradle-wrapper.properties
- [ ] tools/mobile-test/android/testnode/gradlew
- [ ] tools/mobile-test/android/testnode/gradlew.bat
- [ ] tools/mobile-test/android/testnode/settings.gradle
- [ ] tools/mobile-test/ios/node-ios-proxy.sh
- [ ] tools/mobile-test/ios/prepare-ios-tests.sh
- [ ] tools/mobile-test/ios/testnode/testnode.xcodeproj/project.pbxproj
- [ ] tools/mobile-test/ios/testnode/testnode/AppDelegate.h
- [ ] tools/mobile-test/ios/testnode/testnode/AppDelegate.m
- [ ] tools/mobile-test/ios/testnode/testnode/Assets.xcassets/AppIcon.appiconset/Contents.json
- [ ] tools/mobile-test/ios/testnode/testnode/Base.lproj/LaunchScreen.storyboard
- [ ] tools/mobile-test/ios/testnode/testnode/Base.lproj/Main.storyboard
- [ ] tools/mobile-test/ios/testnode/testnode/Info.plist
- [ ] tools/mobile-test/ios/testnode/testnode/NodeRunner.hpp
- [ ] tools/mobile-test/ios/testnode/testnode/NodeRunner.mm
- [ ] tools/mobile-test/ios/testnode/testnode/ViewController.h
- [ ] tools/mobile-test/ios/testnode/testnode/ViewController.m
- [ ] tools/mobile-test/ios/testnode/testnode/main.m

**Deleted**

- [ ] .github/ISSUE_TEMPLATE/1-bug-report.md
- [ ] .github/ISSUE_TEMPLATE/2-feature-request.md
- [ ] .github/ISSUE_TEMPLATE/config.yml
- [ ] .github/PULL_REQUEST_TEMPLATE.md
- [ ] .github/SUPPORT.md
- [ ] .github/workflows/build-windows.yml
- [ ] .github/workflows/linters.yml
- [ ] .github/workflows/misc.yml
- [ ] .github/workflows/pythonpackage.yml
- [ ] .github/workflows/remark-lint-problem-matcher.json
- [ ] .github/workflows/test-linux.yml
- [ ] .github/workflows/test-macos.yml

### CODE REVIEW

**Comment by staltz** [comment]
Hey @gmaclennan, great work, nice to see this moving forward.

I wanted to experiment whether squashing all commits into one was possible, so I started the branch [tiny-history](https://github.com/nodejs-mobile/nodejs-mobile/tree/tiny-history). Currently it has one commit which got everything from nodejs upstream initial commit up until the `v12.19.0` tag. Next, I'll make another big commit that bundles all commits from `v12.19.0` to `v18.10.0`. If that works, I can try putting jaime's commits on top of the `v12.19.0` commit, and then try to merge the `v18.10.0` branch into that.

**Comment by gmaclennan** [comment]
Sounds good @staltz. I realized that v18.10.0 has re-written Android build support, but it's not fully working. Currently the problem I'm hitting is that the v8 build seems to be using system g++ rather than respecting the `CXX` environment variable.

**Comment by staltz** [comment]
@gmaclennan Indeed, https://github.com/nodejs/node/commit/70898b4e67 + https://github.com/nodejs/node/commit/c975c4f674

What if update nodejs-mobile to v16? I know you're trying to get ahead of the curve with v18, but one concern is that nodejs-mobile on v18 would drop support for Android 6.0 and require Android 7.0, which may hurt end users with low-end devices.

I believe that moving forwards, once we figure out a nice workflow to update nodejs upstream into this project, then within the next 12 months we can do the v16 => v18 update. For now, it would be good to just get things working with an active LTS.

**Comment by gmaclennan** [comment]
Yes, that makes sense, especially if v16 can be easier. My thinking had been that since v18 becomes active LTS on Oct 25th, to maybe just leap straight there, but it might be harder. Regarding Android compatibility, that is important. nodejs-mobile currently works with API 21 (Android 5.0) and it would be good to maintain that. Some of Jaime's patches are to enable < API 23 support (e.g. https://github.com/nodejs-mobile/nodejs-mobile/blob/mobile-master/deps/uvwasi/src/uvwasi.c#L1319). Maybe we can keep API 21 compat via some patches.

Let me know how building goes with v16. I managed to merge the diff here — not too complicated but there were a couple of files where the patches were no longer necessary, or needed changed because of code changes. It's the build I'm having issues with, I think because of changes to the v8 build process (which shouldn't be an issue because v8 officially supports android, but it doesn't seem to be picking up the toolchain env)

**Comment by CaryTrivett** [comment]
https://github.com/nodejs/node/commit/6c8c3d89b0a0f2579af4873ef888f1052c660cdc

I see that nodejs supports iOS's PR, does it help with nodejs-mobile migration.

**Comment by staltz** [comment]
I was in the process of updating to v16.18.1 but I realized that that version contains the android-configure rewrite which also bumped the minimum Android SDK.

So instead the "conservative" version would be v16.17.1. I'll work on updating nodejs-mobile to 16.17.1 and I'll postpone the android-configure update headaches.

**Comment by staltz** [comment]
Closing this PR because #9 has been merged

**Pull request closed without merging**
